[package]
name = "storage"
edition.workspace = true
license.workspace = true
publish = false
version.workspace = true

[dependencies]
bytes = "1.12.1"
common = { path = "../common" }
serde.workspace = true
serde_json.workspace = true
simd-json.workspace = true
tokio.workspace = true
tracing.workspace = true
turso = { git = "https://github.com/tursodatabase/turso", rev = "fcb6d7239d1e6dba7ad759819f3eb9b4af567346", default-features = false }
sha2 = "0.11.0"
uuid.workspace = true

[dev-dependencies]
serial_test = "4.0.1"
