app = "dd-traces-8956e096"
primary_region = "ams"
kill_signal = "SIGINT"
kill_timeout = "30s"

[build]
  dockerfile = "Dockerfile"

[env]
  COLLECTOR_OTLP_ENABLED = "true"
  SPAN_STORAGE_TYPE = "memory"

[http_service]
  internal_port = 16686
  force_https = false
  auto_start_machines = true
  auto_stop_machines = false
  min_machines_running = 1

[checks]
  [checks.jaeger_ui]
    type = "tcp"
    port = 16686
    interval = "15s"
    timeout = "2s"
    grace_period = "30s"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "512mb"
