#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
vendor_root="$repo_root/crates/runtime/js/vendor"
lazy_root="$vendor_root/lazy"
manifest="$vendor_root/manifest.txt"
check_only=0
if [[ "${1:-}" == "--check" ]]; then
  check_only=1
  shift
fi
if [[ $# -ne 0 ]]; then
  echo "usage: $0 [--check]" >&2
  exit 2
fi
cargo_home="${CARGO_HOME:-${HOME:?HOME must be set}/.cargo}"
registry_root="$cargo_home/registry/src"

locked_version_for() {
  local package="$1"
  awk -v crate="$package" '
    /^\[\[package\]\]$/ { in_pkg = 1; name = ""; version = ""; next }
    in_pkg && /^name = / {
      line = $0
      sub(/^name = "/, "", line)
      sub(/"$/, "", line)
      name = line
      next
    }
    in_pkg && /^version = / {
      line = $0
      sub(/^version = "/, "", line)
      sub(/"$/, "", line)
      version = line
      next
    }
    in_pkg && name == crate && version != "" {
      print version
      exit
    }
  ' "$repo_root/Cargo.lock"
}

source_dir_for() {
  local package="$1"
  local version="$2"
  local matches=()
  while IFS= read -r path; do
    matches+=("$path")
  done < <(find "$registry_root" -mindepth 2 -maxdepth 2 -type d -name "${package}-${version}" | sort)
  if [[ ${#matches[@]} -ne 1 ]]; then
    echo "expected one Cargo source directory for ${package} ${version}, found ${#matches[@]}" >&2
    exit 1
  fi
  printf '%s\n' "${matches[0]}"
}

# Cargo packages contain the snapshot-ready IIFE form consumed by
# dd_embedded_lazy_js_source. Keep it separate from the ESM sources in the
# parent vendor directories, which deno_core::extension! loads as modules.
for package in deno_webidl deno_web deno_fetch; do
  version="$(locked_version_for "$package")"
  if [[ -z "$version" ]]; then
    echo "missing ${package} version in $repo_root/Cargo.lock" >&2
    exit 1
  fi
  if [[ "$check_only" -eq 0 ]]; then
    source_dir="$(source_dir_for "$package" "$version")"
    mkdir -p "$lazy_root/$package"
    find "$lazy_root/$package" -maxdepth 1 -type f -name '*.js' -delete
    cp "$source_dir"/*.js "$lazy_root/$package/"
  fi
done

if [[ "$check_only" -eq 1 ]]; then
  temporary="$(mktemp "${TMPDIR:-/tmp}/dd-deno-manifest.XXXXXX")"
  trap 'rm -f "$temporary"' EXIT
else
  temporary="${manifest}.tmp"
fi
{
  echo '# Generated by scripts/refresh-deno-sources.sh. Paths are relative to this directory.'
  echo 'format=1'
  for package in deno_webidl deno_web deno_fetch; do
    printf '%s=%s\n' "$package" "$(locked_version_for "$package")"
  done
  echo
  while IFS= read -r file; do
    relative="${file#"$vendor_root/"}"
    printf '%s %s\n' "$(sha256sum "$file" | cut -d' ' -f1)" "$relative"
  done < <(find "$vendor_root" -mindepth 2 -type f -name '*.js' | sort)
} > "$temporary"
if [[ "$check_only" -eq 1 ]]; then
  if ! cmp -s "$temporary" "$manifest"; then
    echo "$manifest is out of date; run scripts/refresh-deno-sources.sh" >&2
    exit 1
  fi
  echo "vendored Deno sources and $manifest are up to date"
else
  mv "$temporary" "$manifest"
  echo "refreshed vendored Deno sources and $manifest"
fi
